spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: true

userservice:
  baseurl: ${USERSERVICE_BASEURL}